apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: jajcoszek/viennacalling-frontend
  newName: jajcoszek/viennacalling-frontend
  newTag: 1.0.2
