apiVersion: v1
kind: Service
metadata:
  name: viennacalling-frontend
spec:
  type: ClusterIP
  selector:
    app: viennacalling-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
